### ISSUE TITLE
main.py in esa_fault_detection scenario has hardcoded paths causing issues with Edge Volumes

### ISSUE THREAD

**Issue by dmc-tech** [microsoft/azure_arc#2735]
> **Note:** For ease of issues and pull requests management and tracking, we kindly ask you to provide a meaningful and concise title to this issue and answer all questions to the best of your ability.

**Is your issue related to a Jumpstart scenario, ArcBox, HCIBox, or Agora?**
[esa_fault_detection](https://github.com/microsoft/azure_arc/tree/main/azure_edge_iot_ops_jumpstart/esa_fault_detection/artifacts/esa_ai)

**Describe the issue or the bug**

When trying to use Azure Arc Edge Volumes, the current container uses hardcoded paths within [main.py](https://github.com/microsoft/azure_arc/blob/main/azure_edge_iot_ops_jumpstart/esa_fault_detection/artifacts/esa_ai/main.py). It does not use the `LOCAL_STORAGE` parameter. Therefore it is trying to write to the read only edge volume, rather than the edgesubvolume. There are no errors in the log and the files are not written to disk.

**To Reproduce**

1. Deploy [Edge Volumes ](https://learn.microsoft.com/en-gb/azure/azure-arc/container-storage/single-node-cluster-edge-volumes?pivots=aks) to the cluster
2. Set up Azure resources and roles

```sh
# Setup cloud identity for edge volume

export EXTENSION_TYPE=${1:-"microsoft.arc.containerstorage"}
EV_ID=$(az k8s-extension list --cluster-name ${ARC_CLUSTER_NAME} --resource-group ${RESOURCE_GROUP} --cluster-type connectedClusters | jq --arg extType ${EXTENSION_TYPE} 'map(select(.extensionType == $extType)) | .[] | .identity.principalId' -r)

# Setup Storage account and containers for demo

if [ $(az storage account check-name --name $STORAGE_ACCOUNT_NAME --query nameAvailable -o tsv) == 'true' ]
then
   az storage account create -n ${STORAGE_ACCOUNT_NAME} -g ${RESOURCE_GROUP} -l ${LOCATION} --sku Standard_LRS
else
  echo "${STORAGE_ACCOUNT_NAME} exists; skipping"
fi

az storage container create --account-name ${STORAGE_ACCOUNT_NAME} -n fault-detection


# Configure blob storage account for Extension Identity

az role assignment create \
  --assignee $EV_ID \
  --role "Storage Blob Data Owner" \
  --scope /subscriptions/${SUB_ID}/resourceGroups/${RESOURCE_GROUP}/providers/Microsoft.Storage/storageAccounts/${STORAGE_ACCOUNT_NAME}
```

4. Deploy PVC and EdgeSubVolume

```yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  ### Create a name for your PVC ###
  name: esa-pvc
  ### Use a namespace that matched your intended consuming pod, or "default" ###
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: cloud-backed-sc
---
apiVersion: "arccontainerstorage.azure.net/v1"
kind: EdgeSubvolume
metadata:
  name: faultdata
spec:
  edgevolume: esa-pvc
  path: faultdata # If you change this path, line 33 in deploymentExample.yaml must be updated. Don't use a preceding slash.
  auth:
    authType: MANAGED_IDENTITY
  storageaccountendpoint: "https://<your storage account>.blob.core.windows.net/"
  container: fault-detection
  ingestPolicy: edgeingestpolicy-default # Optional: See the following instructions if you want to update the ingestPolicy with your own configuration
---
```
5. browse to http://192.168.0.5:8000
6.See that files are not showing in the file list

**Expected behavior**
Files are written to the correct directory on the container.

example of problem code:

```
Line 251: def detect_orientation(frame, contours, base_dir = os.getcwd()):
...
Line 270:  cv2.imwrite("{}/esa_storage/Orientation_{}.png"
                    .format(base_dir, COUNT_OBJECT),
                     frame[y: y + h , x : x + w])
```

example proposed solution: 

```
Line 251: detect_orientation(frame, contours, base_dir = esa_storage):
...
Line 270:  cv2.imwrite("{}/Orientation_{}.png"
                    .format(base_dir, COUNT_OBJECT),
                    frame[y: y + h , x : x + w])
```

**Environment summary**

Using versions deployed with Jumpstart Scenario

**Have you looked at the Troubleshooting and Logs section?**

**Screenshots**

**Additional context**
